name : This is my first workflow
on: 
  workflow_dispatch: 
  inputs:
    name :
    Description : Enter the Name 
    required : true
    age : 
    Description : Enter the Age 
    required : true
    job ID : 
    Descrption : enter job description
    required : true
jobs:
  Display_Data :
    runs-on: Unbuntu-latest
  steps :
    - name : Display Name
      run : echo "${{inputs.name}}"
    - name : Display age 
      run : write-output "my age is ${{inputs.age}}"
    - name : Display Global var
      run : echo "${{vars.HID}}"
    - name : Display Scerets
      run : echo "${{secrets.alibaba_access_key}}"
    - name : Display Env varible 
      env :
        email_id : jyothiastb@gmail.com
      run : echo "$email_id"
        
        
